move PLL reset code from clocks driver to pll driver
raspberrypi/pico-sdk pull request #110
Opened 2021-02-10 18:31 UTC by majbthrd

reset_block() and unreset_block_wait() calls on behalf of pll_init() are moved away from ./src/rp2_common/hardware_clocks/clocks.c and into ./src/rp2_common/hardware_pll/pll.c where they more rightly belong.  This follows the existing conventions already employed in the rtc, spi, uart, i2c, adc driver code.

The assert() calls to verify the validity of parameters are now done before such values are written to the PLL peripheral.

The peripheral state is checked before writing to the peripheral so that a PLL that already matches the provided configuration is not unnecessarily disrupted.

2021-02-11 16:26 UTC, Wren6991 requested changes
This makes a number of changes which are not listed in your description. For example, the USB controller is now not reset on the main boot path. That is a *significant* change that has potential to violate assumptions in the USB stack on a warm boot. If you have exhaustively followed up on the things this could break, it would be helpful to list that in your PR description.

Please also rebase your changes against `develop` and then force-push.

2021-02-11 18:49 UTC, majbthrd commented
The PR has been force rebased to the develop branch as requested.

In addition to what was described previously…

The USB controller reset already happens in the USB driver (rp2040_usb_init), just like rtc, spi, uart, i2c, adc driver code… as well as the PLL driver should this PR be adopted.

The SYSCFG reset does NOT happen as a result of the PR, but no pico-sdk code utilizes this peripheral.  Not resetting SYSCFG has strong benefits when the one core is debugging the other, as the reset disrupts the syscfg→dbgforce register.  Like all the above peripherals, the reset seems best located in the respective driver’s init code.

2021-03-26 16:40 UTC, flit commented
This would be really nice to have in the Pico SDK. Having a drag and drop _standard_ CMSIS-DAP debug probe with no extra hardware is one of the highly attractive features of the Pico, made possible by [pico-debug](/majbthrd/pico-debug). Unfortunately it requires a modified Pico SDK with this patch.

picoprobe is alright, but is slow, requires two Picos, and is non-standard, thus does not work with the majority of debuggers and IDEs. The only mainline release of a debug tool that supports picoprobe that I'm aware of is [pyocd](/pyocd/pyOCD) v0.30 and above.

There are also use cases beyond pico-debug for this PR.

2021-03-26 17:12 UTC, frederikvs commented
This PR enables debugging without requiring external hardware. A brilliant feature that would make the pico hardware **much** more convenient to use for slightly more advanced users. (i.e. those beyond the point of "drag and drop a firmware")

Personally, I feel this feature deserves a place in the getting started manual, right next to the picoprobe solution.

Are there any actions we can take to get this merged?

2021-03-27 01:44 UTC, kilograham commented
@Wren6991 can you take a look, I thought it was awaiting changes to be made

2021-04-06 09:42 UTC, Wren6991 approved these changes
I added a comment to call out the part I was confused about (removing USB/syscfg reset from runtime_init) and removed a couple of register writes that are unnecessary if PLL is in a clean state. Thank you for the patch

2021-04-06 09:42 UTC, merged