add 0xcb helios
raspberrypi/pico-sdk pull request #1174
Opened 2023-01-14 18:25 UTC by Conor-Burns

Adding 0xCB Helios

[source](https://github.com/0xCB-dev/0xCB-Helios)

![](https://github.com/0xCB-dev/0xCB-Helios/raw/main/rev1.0/helios.webp)

2023-01-19 22:21 UTC, kilograham commented on src/boards/include/boards/0xcb_helios.h
> +#define 0XCB_HELIOS
Um; that surely doesn't compile!

2023-01-23 18:51 UTC, kilograham requested changes
as per comment, this header won't compile

2023-05-25 20:06 UTC, kilograham commented
please fix this if you want it

2024-05-19 22:34 UTC, kilograham commented
As OP doesn't seem to be around, I suggest we just add an `_` to the define and commit this (i would have done so in passing, but i can't edit the commit in the original repo)

2024-06-05 18:31 UTC, lurch commented
> As OP doesn't seem to be around, I suggest we just add an `_` to the define and commit this (i would have done so in passing, but i can't edit the commit in the original repo)

Done that in #1724

2024-06-21 19:27 UTC, closed without merging

2024-06-21 19:27 UTC, kilograham commented
#1724 has been merged into develop