Add pico_bootsel_via_double_reset library, fix #87
raspberrypi/pico-sdk pull request #137
Opened 2021-02-16 13:51 UTC by Wren6991

See #87. Pull in the double tap boot library from pico-examples, and add configs and doxygen.

I left the actual code unchanged, but wonder if it is worth adding a couple of compiler barriers.

2021-02-16 13:57 UTC, kilograham requested changes

2021-02-16 13:57 UTC, kilograham commented on src/rp2_common/pico_bootsel_via_double_reset/CMakeLists.txt
> +if (PICO_ON_DEVICE)
this is in rp2_common; guard is not needed

2021-02-16 13:57 UTC, kilograham commented on src/rp2_common/CMakeLists.txt
> +    pico_add_subdirectory(pico_bootsel_via_double_reset)
I guess the ordering of things here isn't obvious, this really belongs before pico_multicore above

2021-02-17 19:49 UTC, kilograham approved these changes
lgtm

2021-02-18 15:20 UTC, lurch commented
Once this has been merged into the `pico-sdk` repo, will the corresponding code in `pico-examples` be updated to match?

2021-02-18 16:12 UTC, Wren6991 commented
> Once this has been merged into the `pico-sdk` repo, will the corresponding code in `pico-examples` be updated to match?

Yes, and that PR exists, and is linked to this PR. Scroll up

2021-02-18 16:12 UTC, merged

2021-02-18 17:07 UTC, hathach commented
Thank you for the PR, this will help small factor board with only 1 reset as button (BOOTSEL can be test pad for recover purpose) :)