Add a cmake function for setting IP addresses
raspberrypi/pico-sdk pull request #1424
Opened 2023-06-13 10:30 UTC by peterharperuk

The fix for the following issue adds some macros to set default ip addresses. These are expressed in hex which is a bit non-obvious to set. So add a macro to convert from a string to the hex representation.

https://github.com/georgerobotics/cyw43-driver/issues/41

2023-06-13 12:04 UTC, lurch commented
Is it worth clarifying that this is for IPv4 addresses?

2023-06-13 13:55 UTC, kilograham requested changes

2023-06-13 13:55 UTC, kilograham commented on src/rp2_common/pico_cyw43_driver/CMakeLists.txt
> +    function(target_set_ip_address TARGET_LIB TARGET_TYPE DEF_NAME IP_ADDRESS_STR)
Function should probably be `pico_set_ip_address`

2024-01-04 16:25 UTC, kilograham requested changes
I'm a bit on the fence about the name; whilst the other `pico_set_` do generally add compile definitions, they do not offer the chance to do so multiple times...

IDK; `pico_configure_ip4_address`? `pico_add_ip4_address`?

2024-01-05 10:58 UTC, peterharperuk commented
pico_configure_ip4_address sounds ok

2024-01-05 15:33 UTC, kilograham approved these changes

2024-01-05 15:33 UTC, merged