Add files via upload
raspberrypi/pico-sdk pull request #1487
Opened 2023-08-28 11:49 UTC by pi-plates

MICROpi board file for pico-sdk

2024-01-12 11:22 UTC, peterharperuk requested changes
You need to push this to the development branch, not master.

2024-01-12 14:50 UTC, lurch commented on src/boards/include/boards/pi-plates_micropi.h
> +// This header may be included by other board headers as "boards/micropi.h"
The name here doesn't match the actual filename?

2024-05-19 22:10 UTC, kilograham approved these changes

2024-06-05 19:10 UTC, lurch commented
With the following small tweaks, this passes the checks I added in #1724 
```patch
 
 // Board definition for the Pi-Plates MICROPi processor board
 
-#ifndef _BOARDS_PIPLATES_MICROPI_H_RP2040
-#define _BOARDS_PIPLATES_MICROPI_H_RP2040
+#ifndef _BOARDS_PI_PLATES_MICROPI_H
+#define _BOARDS_PI_PLATES_MICROPI_H
 
 // For board detection
-#define PIPLATES_MICROPI_RP2040
+#define PI_PLATES_MICROPI
 
 // --- UART ---
 #ifndef PICO_DEFAULT_UART
```

2024-06-21 19:41 UTC, kilograham commented
this was added as part of #1724

2024-06-24 23:20 UTC, lurch commented
> this was added as part of #1724

Umm, no it wasn't.

2024-06-25 02:58 UTC, kilograham commented
is it ready to merge?

2024-06-25 18:23 UTC, lurch commented
IMHO it'll be ready to merge if the changes I suggested earlier are made, i.e. 
```patch
 
 // Board definition for the Pi-Plates MICROPi processor board
 
-#ifndef _BOARDS_PIPLATES_MICROPI_H_RP2040
-#define _BOARDS_PIPLATES_MICROPI_H_RP2040
+#ifndef _BOARDS_PI_PLATES_MICROPI_H
+#define _BOARDS_PI_PLATES_MICROPI_H
 
 // For board detection
-#define PIPLATES_MICROPI_RP2040
+#define PI_PLATES_MICROPI
 
 // --- UART ---
 #ifndef PICO_DEFAULT_UART
```

Are you able to do that @pi-plates or should I just close this PR and create a new one? (Apologies for not making this clear in my previous comment.)

2024-06-25 18:36 UTC, pi-plates commented
Im on VACA and will do this when I get back. I might need a little hand
holding though...

On Tue, Jun 25, 2024, 1:23 PM Andrew Scheller ***@***.***>
wrote:

> IMHO it'll be ready to merge if the changes I suggested earlier are made,
> i.e.
>
>
>  // Board definition for the Pi-Plates MICROPi processor board
>  -#ifndef _BOARDS_PIPLATES_MICROPI_H_RP2040-#define _BOARDS_PIPLATES_MICROPI_H_RP2040+#ifndef _BOARDS_PI_PLATES_MICROPI_H+#define _BOARDS_PI_PLATES_MICROPI_H
>
>  // For board detection-#define PIPLATES_MICROPI_RP2040+#define PI_PLATES_MICROPI
>
>  // --- UART ---
>  #ifndef PICO_DEFAULT_UART
>
> Are you able to do that @pi-plates <https://github.com/pi-plates> or
> should I just close this PR and create a new one? (Apologies for not making
> this clear in my previous comment.)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raspberrypi/pico-sdk/pull/1487#issuecomment-2189679061>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACACCAOCOOBRI3DN6327N6TZJGYSLAVCNFSM6AAAAAA4BJM6RGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBZGY3TSMBWGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-24 09:47 UTC, lurch commented
I've now made the above-mentioned changes directly.

2024-07-24 09:47 UTC, lurch approved these changes
`tools/check_board_header.py` is happy, so approving

2024-07-24 09:48 UTC, pi-plates commented
Thanks a lot.
Jerry Wasinger
Founder, Pi-Plates


On Wed, Jul 24, 2024 at 5:47 AM Andrew Scheller ***@***.***>
wrote:

> I've now made the above-mentioned changes directly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raspberrypi/pico-sdk/pull/1487#issuecomment-2247419773>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACACCAMFTPLSGU6JF6PFA2TZN5Z3FAVCNFSM6AAAAAA4BJM6RGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBXGQYTSNZXGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-24 12:21 UTC, merged