Make it easier to configure default baud rate
raspberrypi/pico-sdk pull request #1648
Opened 2024-02-26 12:38 UTC by peterharperuk

To make stdio logging quicker it's probably a good idea to set the default uart speed 921600, but it's only configurable by adding this define to your project. Make it configurable from the cmake command line.

2024-05-19 21:38 UTC, kilograham reviewed
should probably add a `PICO_CMAKE_CONFIG` so it appears in the docs (or ought to!)

2024-05-20 14:01 UTC, lurch commented
> should probably add a `PICO_CMAKE_CONFIG` so it appears in the docs (or ought to!)

`PICO_DEFAULT_UART_BAUD_RATE` _does_ already appear on page 482 of https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf if that's what you were referring to?
Or am I confusing "Appendix B: SDK configuration" with "Appendix C: CMake build
configuration" ?

2024-05-20 14:19 UTC, peterharperuk commented
I think you can only set PICO_DEFAULT_UART_BAUD_RATE if you add it to your CMake file. I was suggesting you can set it by adding PICO_DEFAULT_UART_BAUD_RATE=xyz to the CMake command line

2024-06-05 01:02 UTC, kilograham requested changes
pls add PICO_CMAKE_CONFIG

2024-06-10 14:51 UTC, peterharperuk commented
I've added PICO_CMAKE_CONFIG to the CMakeLists.txt file. As @lurch points out - it's already in the header file

2024-06-21 19:31 UTC, kilograham approved these changes

2024-06-21 19:31 UTC, merged