Export linker scripts in the bazel build.
raspberrypi/pico-sdk pull request #1944
Opened 2024-09-23 19:26 UTC by davexroth

Export linker scripts in the bazel build.

Make the rp2024 and rp2350 linker scripts available in downstream projects bazel builds.

2024-09-23 20:14 UTC, armandomontanez requested changes

2024-09-23 20:14 UTC, armandomontanez commented on src/rp2_common/pico_crt0/rp2040/BUILD.bazel
> +exports_files(
Nit: traditionally `exports_files` is always placed just below the `package` declaration. It's possible buildifier has a check for this, don't remember off the top of my head.

2024-09-23 20:14 UTC, armandomontanez commented on src/rp2_common/pico_crt0/rp2350/BUILD.bazel
> +exports_files(
ditto

2024-09-23 21:58 UTC, armandomontanez approved these changes
LGTM, thanks!

@kilograham ready to go when you are.

2024-09-25 22:19 UTC, lurch commented
nit: Commit-message says "rp2024" instead of "rp2040", but that probably doesn't matter.

2024-09-26 01:23 UTC, davexroth commented
> nit: Commit-message says "rp2024" instead of "rp2040", but that probably doesn't matter.

fixed.

2024-09-26 10:07 UTC, lurch commented
You edited the PR message, not the commit message :wink:

2024-09-26 18:23 UTC, davexroth commented
> You edited the PR message, not the commit message 😉 But like I said, this doesn't really matter.

sorry, should have said "sort of fixed" :) Fixing up old commit message is a bit of a pain, and I don't know if this repo allows force commits.

2024-09-28 04:50 UTC, kilograham approved these changes

2024-09-28 04:50 UTC, merged