Cleanup/clarification of PIO behavior with >32 pins
raspberrypi/pico-sdk pull request #2085
Opened 2024-11-22 03:32 UTC by kilograham

2024-11-22 11:12 UTC, peterharperuk commented on src/rp2_common/hardware_pio/include/hardware/pio.h
> + * `pio_sm_` methods that directly affect the hardware always take _real_ pin numbers in the full range, however:
Is it worth saying that sm_ methods also take _real_ pin numbers?

2024-11-22 11:14 UTC, peterharperuk commented on src/rp2_common/hardware_pio/include/hardware/pio.h
> + * `pio_sm_` methods that directly affect the hardware always take _real_ pin numbers in the full range, however:
ah - you've said that below - ignore

2024-11-22 12:38 UTC, peterharperuk approved these changes
Looks good to me, and fixes the uart_rx example!

2024-11-22 13:00 UTC, peterharperuk requested changes
ah - I think pio_sm_set_pindirs_with_mask64 is shifting twice. It shifts by pio_get_gpio_base then calls pio_sm_set_pindirs_with_mask_internal which shifts again. Removing the shift from pio_sm_set_pindirs_with_mask_internal fixes this. uart_tx can be used to test this.

2024-11-22 14:17 UTC, peterharperuk commented on src/rp2_common/hardware_pio/pio.c
> +#if PICO_PIO_USE_GPIO_BASE
These lines need to be removed?

2024-11-22 18:19 UTC, peterharperuk approved these changes
Seems to work nicely

2024-11-22 19:13 UTC, merged

2024-11-25 01:00 UTC, lurch commented on src/rp2_common/hardware_pio/pio.c
> +#ifndef pio_sm_set_pins_internal
I'm sure this must be a stupid question, but why is line 243 doing
```
#ifndef pio_sm_set_pins_internal
```
when line 221 says
```
void pio_sm_set_pins_internal(PIO pio, uint sm, uint32_t pins) {
```
?