Release the lock in mbedtls_sha256_free if it was not released already
raspberrypi/pico-sdk pull request #2105
Opened 2024-11-27 11:25 UTC by nilswiersma

Release the lock in `mbedtls_sha256_free` if it was not released already. Requires making `pico_sha256_unlock` include-able. Fixes #2103.

2024-11-27 15:08 UTC, kilograham requested changes
I think i'd prefer to expose something like

```
void pico_sha256_cleanup(pico_sha256_state_t *state, sha256_result_t *out) {
   if (state->locked) {
       pico_sha256_unlock(state);
   }
}
```

2025-01-22 11:55 UTC, peterharperuk approved these changes

2025-01-22 11:55 UTC, peterharperuk commented
I wrote a test for this. I'll push this if you want @kilograham

2025-01-22 17:10 UTC, kilograham commented on src/rp2_common/pico_sha256/include/pico/sha256.h
> + * Fails if the internal lock was not claimed.
Does it really fail ?

2025-01-29 13:06 UTC, peterharperuk commented on src/rp2_common/pico_sha256/include/pico/sha256.h
> + * Fails if the internal lock was not claimed.
No - will fix

2025-01-29 15:37 UTC, kilograham approved these changes

2025-01-31 17:41 UTC, merged