Add gpio_get_out_level() accessor, and correct SIO GPIO_OUT struct ty…
raspberrypi/pico-sdk pull request #247
Opened 2021-03-11 14:21 UTC by Wren6991

…pe from WO to RW

See #163

2021-03-12 08:45 UTC, lurch commented
https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_regs/include/hardware/regs/sio.h#L112 says the OE registers are RW too - should this PR also modify `gpio_oe` and `gpio_hi_oe` to be `io_rw_32`? (`gpio_oe` gets read from at https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_gpio/include/hardware/gpio.h#L454 and https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_gpio/include/hardware/gpio.h#L487 so I guess there must be nothing in the SDK to prevent you from reading from a `io_wo_32` ?)

And just for "debug use" completeness, is it worth adding accessor functions for reading the INOVER and OUTOVER registers?

2021-03-13 15:20 UTC, kilograham requested changes

2021-03-13 15:20 UTC, kilograham commented on src/rp2_common/hardware_gpio/include/hardware/gpio.h
> +    return !!(sio_hw->gpio_out & 1u << gpio);
really trying to be consistent adding parenthesis to clarify things like & << precedence

2021-03-22 17:54 UTC, kilograham approved these changes

2021-03-22 17:54 UTC, merged