Use pico_unique_id as the USB device serial number
raspberrypi/pico-sdk pull request #280
Opened 2021-03-24 16:12 UTC by earlephilhower

Use the pico_unique_id to generate a unique serial number for the
STDIO_USB device, allowing for individual boards to be identified.

2021-03-24 17:35 UTC, lurch commented
I thought this was a duplicate, but I did a search and found https://github.com/raspberrypi/picoprobe/pull/8 which is actually slightly different :laughing: 

Can you rebase this against `develop-1.1.1` please?

2021-03-24 17:50 UTC, earlephilhower commented
@lurch  By inspection it looks like we get the same results.  `strcat` is heavier weight, but this generation is called exactly 1 time and if you've got `stdio` running then `strcat` is along for the ride anyway (i.e. no add'l code space increase).

2021-03-24 17:59 UTC, lurch commented
I wonder if it's worth adding a "common" `pico_unique_id_to_string(char* str, uint strlen)` function to the `pico_unique_id` lib? :shrug: (For bonus points maybe you could copy only a subset of the unique_id if strlen is too short, and start repeating the unique_id if strlen is too long? :laughing: )

2021-03-24 23:51 UTC, earlephilhower commented
As a lowly end user I was hesitant to suggest a new API call, but your suggestion does make sense (modulo the repeating copies if the buffer is too long...that seems like not the right thing to do).  Let me adjust this PR accordingly.  Then, if merged, picoprobe can be modified to use this new API and only 1 copy of the code will exist (yay!).

2021-03-24 23:55 UTC, kilograham requested changes

2021-03-24 23:55 UTC, kilograham commented on src/rp2_common/pico_stdio_usb/stdio_usb_descriptors.c
> +        for (int i = 0; i < PICO_UNIQUE_BOARD_ID_SIZE_BYTES; i++) {
yeah, we should pull in printf etc. just to have the serial number. please replace with a trivial loop to fill in the hex values directly

2021-03-24 23:57 UTC, kilograham commented
ah i see this is concurrent editing... i'm ok with adding a helper function to do the trivial loop since it seems useful.

2021-03-24 23:58 UTC, kilograham commented
also please rebase this onto develop not develop-1.1.1 @lurch steered you wrongly!

2021-03-25 02:20 UTC, earlephilhower commented
Closing due to being stuck in a weird git rebase heck.

New PR #281 supersedes with the suggested new API and low-code implementation.

2021-03-25 02:20 UTC, closed without merging