Fix path + typo in README.md
raspberrypi/pico-sdk pull request #347
Opened 2021-04-19 00:47 UTC by Exr0n

My first PR on a large, public project.. please let me know if I did something wrong :)

2021-04-19 01:12 UTC, lurch commented on README.md
> +          include(pico-sdk/external/pico_sdk_init.cmake)
I think this was correct as-is? https://github.com/raspberrypi/pico-sdk/blob/master/pico_sdk_init.cmake

2021-04-27 00:26 UTC, kilograham requested changes
Note also, please change to be on top of branch "develop"

2021-04-27 00:26 UTC, kilograham commented on README.md
> +          include(pico-sdk/external/pico_sdk_init.cmake)
yeah this change is incorrect; please remove

2021-05-02 20:14 UTC, kilograham approved these changes

2021-05-02 20:14 UTC, merged