- interp_ fixes
raspberrypi/pico-sdk pull request #428
Opened 2021-05-21 12:52 UTC by Reneg973

- fix interp_claim_lane (in case of interp1 and lane==1 "bit" was 0b11 instead of 0b1000)

- added missing function interp_unclaim_lane_mask()

2021-05-21 18:08 UTC, kilograham requested changes
we've already discussed not adding const to hardware pointers in another issue; remove these as the rest looks more useful.

2021-05-22 06:36 UTC, Reneg973 commented
> we've already discussed not adding const to hardware pointers in another issue; remove these as the rest looks more useful.

Well, it was worth a try - you may have seen that I've splitted the const correct patch from the real bug.
It just that unlovely because my emerging const correct C++ classes need to spam a lot of const_cast<>s

2021-05-22 11:47 UTC, kilograham commented
> Well, it was worth a try - you may have seen that I've splitted the const correct patch from the real bug.
Are you referring to the previous PR?

> it's just that unlovely because my emerging const correct C++ classes need to spam a lot of const_cast<>s
The last I checked, your previous _const_ changes caused a bunch of new warnings. perhaps post a sample of your C++ code, so I can see where the pain is, and see if I am moved, I'm guessing this is const methods. Still philosophically i'm not convinced that what you call "correct" is actually philosophically so, since many thing (particularly interp) have side effects on read.

2021-05-22 20:52 UTC, Reneg973 commented
> Are you referring to the previous PR?

No, I split this PR into 2 commits, first to fix the bug and second to add some costs.

> The last I checked, your previous _const_ changes caused a bunch of new warnings. perhaps post a sample of your C++ code, so I can see where the pain is, and see if I am moved, I'm guessing this is const methods. Still philosophically ...

I know and I am sorry that I just compiled my code and not all references to see where build problems exist. 
May it be possible to add some auto checks for PRs?

I don't want to discuss const. It may be used or may be not. It is just if you worked many years with it you don't want to miss it anymore (like me). And it is still not clear which strategy picosdk is following, as const is already used, but more or less sporadically.

2021-05-24 21:52 UTC, kilograham approved these changes

2021-05-24 21:56 UTC, merged