Make sure OUT_STICKY is not set when setting pins / pindirs
raspberrypi/pico-sdk pull request #989
Opened 2022-08-25 17:49 UTC by jannic

To avoid the issue described in #988, temporarily clear the OUT_STICKY bit in the affected functions, and restore the value later.
(Note that I didn't test this fix with the C SDK. It's a port of https://github.com/rp-rs/rp-hal/pull/432 which was tested on real hardware, but I might have introduced bugs when porting it to C - my C has become quite rusty, pun intended... Please review carefully)

Fixes #988

2022-08-28 23:02 UTC, ithinuel submitted a review, later dismissed

2022-09-12 18:33 UTC, kilograham requested changes

2022-09-12 18:33 UTC, kilograham commented on src/rp2_common/hardware_pio/pio.c
> +    pio->sm[sm].execctrl = pio->sm[sm].execctrl & ~(1 << PIO_SM0_EXECCTRL_OUT_STICKY_LSB);
please use `hw_clear_bits`

2022-09-12 20:01 UTC, jannic commented
(Sorry, updated only one instance at first, fixed now.)

2022-10-16 21:39 UTC, kilograham approved these changes

2022-10-16 21:39 UTC, merged